CREATE DATABASE IF NOT EXISTS coeus;
CREATE DATABASE IF NOT EXISTS hummer;
CREATE DATABASE IF NOT EXISTS diseasecard;

GRANT ALL PRIVILEGES ON coeus.* TO 'demo'@'%' IDENTIFIED BY 'demo';
FLUSH PRIVILEGES;

GRANT ALL PRIVILEGES ON coeus.* TO 'demo'@'localhost' IDENTIFIED BY 'demo';
FLUSH PRIVILEGES;

GRANT ALL PRIVILEGES ON *.* TO 'diseasecard'@'%' IDENTIFIED BY 'diseasecard';
FLUSH PRIVILEGES;

GRANT ALL PRIVILEGES ON *.* TO 'diseasecard'@'localhost' IDENTIFIED BY 'diseasecard';
FLUSH PRIVILEGES;

GRANT ALL PRIVILEGES ON hummer.* TO 'hummer'@'%' IDENTIFIED BY 'hummer';
FLUSH PRIVILEGES;

GRANT ALL PRIVILEGES ON hummer.* TO 'hummer'@'localhost' IDENTIFIED BY 'hummer';
FLUSH PRIVILEGES;